{% set version = "2025.1" %}
{% set python_min = python_min|default("3.6") %}

package:
  name: pudb
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pudb/pudb-{{ version }}.tar.gz
  sha256: a528b29c69ce8b182a337872c5f046071f6d68d3415c6d7bf53bd27c264f58d0

build:
  number: 0
  entry_points:
    - pudb = pudb.run:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python
requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - urwid >=2.4
    - urwid_readline
    - packaging >=20.0
    - pygments >=2.7.4
    - jedi >=0.18,<1

test:
  requires:
    - pytest-mock
    - python {{ python_min }}
  imports:
    - pudb

  commands:
    - pudb --help
  source_files:
    - pudb/test
  commands:
    - cd pudb/test && python -m pytest

about:
  home: https://pypi.org/project/pudb/
  license: MIT
  license_file: LICENSE
  summary: 'A full-screen, console-based Python debugger'
  dev_url: https://github.com/inducer/pudb
  doc_url: https://documen.tician.de/pudb/

extra:
  recipe-maintainers:
    - jeongseok-meta
    - asmeurer
    - inducer
    - matthiasdiener
